# Generated by Django 2.2.5 on 2020-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateField(null=True)),
                ('read_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'BookInfo_db',
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.SmallIntegerField(choices=[(0, 'BOY'), (1, 'GIRL')])),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PersonInfo_db',
            },
        ),
    ]
