# Generated by Django 2.2.5 on 2020-12-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('read_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('writer', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'BOY'), (1, 'GIRL'), (2, 'UNKNOWN')])),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.BookInfo')),
            ],
        ),
    ]
