# Generated by Django 2.2.5 on 2020-12-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='BookInfo',
        ),
        migrations.AlterModelTable(
            name='personinfo',
            table='PersonInfo',
        ),
    ]
